In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, confusion_matrix

In [2]:
dataset = pd.read_csv(r'/Users/sehan/Documents/Data_Collection-26-08/binarytop10.csv')

In [4]:
dataset.head()

,Unnamed: 0,Seq,sTtl,Offset,TcpRtt,AckDat,e,icmp,tcp,INT,RST,Label
0,0,1,58.0,128,0.0,0.0,1.0,1.0,0.0,0.0,0.0,Benign
1,1,2,58.0,232,0.0,0.0,1.0,1.0,0.0,0.0,0.0,Benign
2,2,3,117.0,336,0.0,0.0,1.0,0.0,0.0,0.0,0.0,Benign
3,3,4,117.0,440,0.0,0.0,1.0,0.0,0.0,0.0,0.0,Benign
4,4,5,117.0,544,0.0,0.0,1.0,0.0,0.0,0.0,0.0,Benign

In [6]:
dataset = dataset.fillna(dataset.median())
display(dataset)

,Unnamed: 0,Seq,sTtl,Offset,TcpRtt,AckDat,e,icmp,tcp,INT,RST,Label
0,0,1,58.0,128,0.0,0.0,1.0,1.0,0.0,0.0,0.0,Benign
1,1,2,58.0,232,0.0,0.0,1.0,1.0,0.0,0.0,0.0,Benign
2,2,3,117.0,336,0.0,0.0,1.0,0.0,0.0,0.0,0.0,Benign
3,3,4,117.0,440,0.0,0.0,1.0,0.0,0.0,0.0,0.0,Benign
4,4,5,117.0,544,0.0,0.0,1.0,0.0,0.0,0.0,0.0,Benign
...,...,...,...,...,...,...,...,...,...,...,...,...
1215885,1215885,1,252.0,190300,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
1215886,1215886,3,255.0,190392,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
1215887,1215887,764,64.0,190496,0.0,0.0,1.0,0.0,1.0,0.0,0.0,Benign
1215888,1215888,3,255.0,190704,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
1215889,1215889,1,252.0,190808,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign

In [7]:
dataset = dataset.iloc[: , 1:]
display(dataset)

,Seq,sTtl,Offset,TcpRtt,AckDat,e,icmp,tcp,INT,RST,Label
0,1,58.0,128,0.0,0.0,1.0,1.0,0.0,0.0,0.0,Benign
1,2,58.0,232,0.0,0.0,1.0,1.0,0.0,0.0,0.0,Benign
2,3,117.0,336,0.0,0.0,1.0,0.0,0.0,0.0,0.0,Benign
3,4,117.0,440,0.0,0.0,1.0,0.0,0.0,0.0,0.0,Benign
4,5,117.0,544,0.0,0.0,1.0,0.0,0.0,0.0,0.0,Benign
...,...,...,...,...,...,...,...,...,...,...,...
1215885,1,252.0,190300,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
1215886,3,255.0,190392,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
1215887,764,64.0,190496,0.0,0.0,1.0,0.0,1.0,0.0,0.0,Benign
1215888,3,255.0,190704,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
1215889,1,252.0,190808,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign

In [8]:
X = dataset.iloc[:,0:9].values
y = dataset.iloc[:,10].values

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=0)

In [10]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

In [11]:
import time
from sklearn.neural_network import MLPClassifier
MLP = MLPClassifier(hidden_layer_sizes=(10,20,10), max_iter=1000)
start = time.time()
MLP.fit(X_train, y_train)
stop = time.time()
print(f"Training time: {stop - start}s")

Training time: 350.67145681381226s

In [12]:
start = time.time()
y_pred = MLP.predict(X_test)
stop = time.time()
y_pred
print(f"Prediction time: {stop - start}s")

Prediction time: 0.43076205253601074s

In [73]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred, digits=4))
print(accuracy_score(y_test, y_pred))

[[  6187   3791]
 [  3825 241559]]
              precision    recall  f1-score   support

           0     0.6180    0.6201    0.6190      9978
           1     0.9845    0.9844    0.9845    245384

    accuracy                         0.9702    255362
   macro avg     0.8013    0.8022    0.8017    255362
weighted avg     0.9702    0.9702    0.9702    255362

0.9701756721830186

In [29]:
from sklearn.metrics import roc_curve, auc

model_fpr, model_tpr, threshold = roc_curve(y_test, y_pred[:,1])
auc_model = auc(model_fpr, model_tpr)

plt.figure(figsize=(5, 5), dpi=100)
plt.plot(model_fpr, model_tpr, linestyle='-', label='MLP (auc = %0.3f)' % auc_model)
plt.plot([0, 1], [0, 1], color="darkorange", lw=2, linestyle="--")
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')

plt.legend()
plt.show()

NameError: name 'plt' is not defined